AddCSLuaFile()

hook.Add("PopulateToolMenu", "CATManualPickup", function()
	spawnmenu.AddToolMenuOption("Options", "Chen's Addons", "catmanualpickup", "Manual Pickup & Swap", "", "", function(panel)
		local sv = vgui.Create("DForm")
		panel:AddItem(sv)
		sv:SetName("Server")
		sv:CheckBox("Manually pick up weapons", "catpickup_weapons")
		sv:CheckBox("Manually pick up ammo and items", "catpickup_items")
		sv:NumSlider("Weapon auto-clear time", "catpickup_clearweapons", 0, 600, 1)
		sv:ControlHelp("Automatically clear dropped weapons after # seconds. 0 to not clear.")
	end)
end)

-- hook.Add("Tick", "CATManualPickup", function()
	-- print("hi")
-- end)